language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -U nltk
# command to run tests
script:
  - cd text2graph && ./test && cd ../ # or py.test for Python versions 3.5 and below
